version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./school.sql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  FROM java:8  
  COPY . /
  WORKDIR /  
  RUN javac DockerConnectMySQL.java
  CMD ["java", "-classpath", "mysql-connector-java-5.1.6.jar:.","DockerConnectMyS
