version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
      
  java:
    image: openjdk:7
    depends_on:
    - db
    volumes:
    - /home/crismon-01/Documenti/TESI/Docker/mysqlLogin:/usr/src/myapp 
    command: bash -c "cd /usr/src/myapp && java -jar LogiIn.jar"
